print("===================================")
print("Toko Roti\t\t")
print("===================================")
nama = input("Masukan Nama Pembeli\t : ")
kode = input("Masukan Kode Roti\t : ")
harga = float(input("Masukan Harga Roti\t : "))  
jumlah = int(input("Masukan Jumlah Roti\t : ")) 
hasil = harga * jumlah  
print("===================================")
print("Hasil Cetak Data\t\t")
print("===================================")
print("Nama Pembeli\t\t :", nama)
print("Kode Roti\t\t :", kode)
print("Harga Roti\t\t :", harga)
print("Jumlah\t\t\t :", jumlah)
print("Total\t\t\t :", hasil)